<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Phalcon Tutorial</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body  style="background-image: url('../../public/images/bg.avif'); background-repeat:no-repeat; background-size:cover ">
<div class="container-fluid">
    <?php echo $this->getContent(); ?>
</div>
</body>
</html>